const mongoose = require('mongoose');

module.exports = 
[
 {
      "name": "Submariner",
      "icon_url": "https://static.ancientgaming.io/images/Rolex%20Submariner%20Black.png",
      "description": "",
      "brand": "Rolex",
      "value": 58086,
      "usable": true,
      "obtainable": true,
      "withdrawable": true,
      "rarity": "legendary",
      "currency": "USD",
      "shippingCost": 0,
      "type": "IRL",
      "min_value": 58086,
      "max_value": 58086,
      "category": null,  
      "min_rarity": "legendary",
      "max_rarity": "legendary",
      "released_at": new Date("2017-09-09T03:00:00.000Z"),
      "market": null,
      "category": [
          new mongoose.Types.ObjectId('636c84ece4830d466abadc0c'),
          new mongoose.Types.ObjectId('636c84ece4830d466abadc0d'),
          new mongoose.Types.ObjectId('636c84ece4830d466abadc11')
      ]
  },
  {
      "name": "Daytona",
      "icon_url": "https://static.ancientgaming.io/images/Rolex%20DAYTONA%20white%20black.png",
      "description": "",
      "brand": "Rolex",
      "value": 50295,
      "usable": true,
      "obtainable": true,
      "withdrawable": true,
      "rarity": "legendary",
      "currency": "USD",
      "shippingCost": 0,
      "type": "IRL",
      "min_value": 50295,
      "max_value": 50295,
      "category": null,  
      "min_rarity": "legendary",
      "max_rarity": "legendary",
      "released_at": new Date("2017-09-09T03:00:00.000Z"),
      "market": null,
      "category": [
          new mongoose.Types.ObjectId('636c84ece4830d466abadc13'),
          new mongoose.Types.ObjectId('636c84ece4830d466abadc15')
      ]
  },
  {
      "name": "Raised Baguette Cuban Link Bracelet 14k",
      "icon_url": "https://static.ancientgaming.io/images/Raised%20Baguette%20Cuban%20Link%20Bracelet%2014k%2020.50ctw.png",
      "description": "",
      "brand": "Icebox",
      "value": 46000,
      "usable": true,
      "obtainable": true,
      "withdrawable": true,
      "rarity": "legendary",
      "currency": "USD",
      "shippingCost": 0,
      "type": "IRL",
      "min_value": 46000,
      "max_value": 46000,
      "category": null,  
      "min_rarity": "legendary",
      "max_rarity": "legendary",
      "released_at": new Date("2017-09-09T03:00:00.000Z"),
      "market": null,
      "category": [
          new mongoose.Types.ObjectId('636c84ece4830d466abadc19'),
          new mongoose.Types.ObjectId('636c84ece4830d466abadc1a'),
          new mongoose.Types.ObjectId('636c84ece4830d466abadc1e'),
          new mongoose.Types.ObjectId('636c84ece4830d466abadc1f')
      ]
  },
  {
      "name": "Sky-Dweller",
      "icon_url": "https://static.ancientgaming.io/images/Rolex%20Sky-Dweller.png",
      "description": "",
      "brand": "Rolex",
      "value": 29988,
      "usable": true,
      "obtainable": true,
      "withdrawable": true,
      "rarity": "legendary",
      "currency": "USD",
      "shippingCost": 0,
      "type": "IRL",
      "min_value": 29988,
      "max_value": 29988,
      "category": null,  
      "min_rarity": "legendary",
      "max_rarity": "legendary",
      "released_at": new Date("2017-09-09T03:00:00.000Z"),
      "market": null,
      "category": [
          new mongoose.Types.ObjectId('636c84ece4830d466abadc1e'),
          new mongoose.Types.ObjectId('636c84ece4830d466abadc22')
      ]
  },
  {
      "name": "GMT-MASTER II \"PEPSI\"",
      "icon_url": "https://static.ancientgaming.io/images/Rolex%20GMT-Master%20ll%20PEPSI.png",
      "description": "",
      "brand": "Rolex",
      "value": 29442,
      "usable": true,
      "obtainable": true,
      "withdrawable": true,
      "rarity": "legendary",
      "currency": "USD",
      "shippingCost": 0,
      "type": "IRL",
      "min_value": 29442,
      "max_value": 29442,
      "category": null,  
      "min_rarity": "legendary",
      "max_rarity": "legendary",
      "released_at": new Date("2017-09-09T03:00:00.000Z"),
      "market": null,
      "category": [
        
      ]
  },
  {
      "name": "Aviator Leather Jacket",
      "icon_url": "https://static.ancientgaming.io/images/Brunello%20Cucinelli%20Aviator%20Leather%20Jacket.png",
      "description": "",
      "brand": "Brunello Cucinelli",
      "value": 8528.33,
      "usable": true,
      "obtainable": true,
      "withdrawable": true,
      "rarity": "legendary",
      "currency": "USD",
      "shippingCost": 0,
      "type": "IRL",
      "min_value": 8528.33,
      "max_value": 8528.33,
      "category": null,  
      "min_rarity": "legendary",
      "max_rarity": "legendary",
      "released_at": new Date(),
      "market": null,
      "category": [
          new mongoose.Types.ObjectId('636c84ece4830d466abadc16'),
          new mongoose.Types.ObjectId('636c84ece4830d466abadc18')
      ]
  },
  {
      "name": "Datejust 31",
      "icon_url": "https://static.ancientgaming.io/images/Rolex%20DATEJUST%2031.png",
      "description": "",
      "brand": "Rolex",
      "value": 12852,
      "usable": true,
      "obtainable": true,
      "withdrawable": true,
      "rarity": "legendary",
      "currency": "USD",
      "shippingCost": 0,
      "type": "IRL",
      "min_value": 12852,
      "max_value": 12852,
      "category": null,  
      "min_rarity": "legendary",
      "max_rarity": "legendary",
      "released_at": new Date("2017-09-09T03:00:00.000Z"),
      "market": null,
      "category": [
        new mongoose.Types.ObjectId('636c84ece4830d466abadc20')
      ]
  },
  {
      "name": "Medium Full Diamond Signature Bangle Bracelet 14k",
      "icon_url": "https://static.ancientgaming.io/images/Icebox%20Medium%20Full%20Diamond%20Signature%20Bangle%20Bracelet%2014k%20Rose%20Gold.png",
      "description": "",
      "brand": "Icebox",
      "value": 12250,
      "usable": true,
      "obtainable": true,
      "withdrawable": true,
      "rarity": "legendary",
      "currency": "USD",
      "shippingCost": 0,
      "type": "IRL",
      "min_value": 12250,
      "max_value": 12250,
      "category": null,  
      "min_rarity": "legendary",
      "max_rarity": "legendary",
      "released_at": new Date("2017-09-09T03:00:00.000Z"),
      "market": null,
      "category": [
        new mongoose.Types.ObjectId('636c84ece4830d466abadc22')
      ]
  },
  {
      "name": "Jordan 1 Retro High Off-White Chicago",
      "icon_url": "https://static.ancientgaming.io/images/Jordan%201%20Retro%20High%20Off-White%20Chicago1.png",
      "description": "",
      "brand": "Nike",
      "value": 6290,
      "usable": true,
      "obtainable": true,
      "withdrawable": true,
      "rarity": "legendary",
      "currency": "USD",
      "shippingCost": 0,
      "type": "IRL",
      "min_value": 6290,
      "max_value": 6290,
      "category": null,  
      "min_rarity": "legendary",
      "max_rarity": "legendary",
      "released_at": new Date("2017-09-09T03:00:00.000Z"),
      "market": null,
      "category": [
        new mongoose.Types.ObjectId('636c84ece4830d466abadc23')
      ]
  },
  {
      "name": "Box Logo Hooded Sweatshirt",
      "icon_url": "https://static.ancientgaming.io/images/Supreme%20x%20Louis%20Vuitton%20Box%20Logo%20Hooded%20Sweatshirt.png",
      "description": "",
      "brand": "Supreme x Louis Vuitton",
      "value": 6240,
      "usable": true,
      "obtainable": true,
      "withdrawable": true,
      "rarity": "legendary",
      "currency": "USD",
      "shippingCost": 0,
      "type": "IRL",
      "min_value": 6240,
      "max_value": 6240,
      "category": null,  
      "min_rarity": "legendary",
      "max_rarity": "legendary",
      "released_at": new Date("2017-06-29T16:00:00.000Z"),
      "market": null,
      "category": [
        new mongoose.Types.ObjectId('636c84ece4830d466abadc15')
      ]
  },
  {
      "name": "Datejust 36",
      "icon_url": "https://static.ancientgaming.io/images/Rolex%20Datejust%2036%20M.png",
      "description": "",
      "brand": "Rolex",
      "value": 19173,
      "usable": true,
      "obtainable": true,
      "withdrawable": true,
      "rarity": "legendary",
      "currency": "USD",
      "shippingCost": 0,
      "type": "IRL",
      "min_value": 19173,
      "max_value": 19173,
      "category": null,  
      "min_rarity": "legendary",
      "max_rarity": "legendary",
      "released_at": new Date("2020-06-25T16:00:00.000Z"),
      "market": null,
      "category": [
        new mongoose.Types.ObjectId('636c84ece4830d466abadc16')
      ]
  },
  {
      "name": "Cartier Brown Tinted Lens Sunglasses 14K",
      "icon_url": "https://static.ancientgaming.io/images/Cartier%20Brown%20Tinted%20Lens%20Sunglasses%2014K%203.00ctw.png",
      "description": "",
      "brand": "Icebox",
      "value": 10400,
      "usable": true,
      "obtainable": true,
      "withdrawable": true,
      "rarity": "legendary",
      "currency": "USD",
      "shippingCost": 0,
      "type": "IRL",
      "min_value": 10400,
      "max_value": 10400,
      "category": null,  
      "min_rarity": "legendary",
      "max_rarity": "legendary",
      "released_at": new Date("2020-06-25T16:00:00.000Z"),
      "market": null,
      "category": [
        new mongoose.Types.ObjectId('636c84ece4830d466abadc19')
      ]
  },
  {
      "name": "Medium Half Diamond Cuban Bangle Bracelet 14K",
      "icon_url": "https://static.ancientgaming.io/images/Icebox%20Medium%20Half%20Diamond%20Cuban%20Bangle%20Bracelet%2014K.png",
      "description": "",
      "brand": "Icebox",
      "value": 7000,
      "usable": true,
      "obtainable": true,
      "withdrawable": true,
      "rarity": "legendary",
      "currency": "USD",
      "shippingCost": 0,
      "type": "IRL",
      "min_value": 7000,
      "max_value": 7000,
      "category": null,  
      "min_rarity": "legendary",
      "max_rarity": "legendary",
      "released_at": new Date("2020-06-25T16:00:00.000Z"),
      "market": null,
      "category": [
        new mongoose.Types.ObjectId('636c84ece4830d466abadc1a')
      ]
  },
  {
      "name": "Giant Damier Waves MNGM Denim Jacket",
      "icon_url": "https://static.ancientgaming.io/images/Louis%20Vuitton%20x%20Nigo%20Giant%20Damier%20Waves%20MNGM%20Denim%20Jacket.png",
      "description": "",
      "brand": "Louis Vuitton x Nigo",
      "value": 4770,
      "usable": true,
      "obtainable": true,
      "withdrawable": true,
      "rarity": "legendary",
      "currency": "USD",
      "shippingCost": 0,
      "type": "IRL",
      "min_value": 4770,
      "max_value": 4770,
      "category": null,  
      "min_rarity": "legendary",
      "max_rarity": "legendary",
      "released_at": new Date("2020-06-25T16:00:00.000Z"),
      "market": null,
      "category": [
        new mongoose.Types.ObjectId('636c84ece4830d466abadc0f')
      ]
  },
  {
      "name": "1 High OG SP fragment design x Travis Scott",
      "icon_url": "https://static.ancientgaming.io/images/Jordan%201%20High%20OG%20SP%20fragment%20design%20x%20Travis%20Scott.png",
      "description": "",
      "brand": "Jordan",
      "value": 3248,
      "usable": true,
      "obtainable": true,
      "withdrawable": true,
      "rarity": "legendary",
      "currency": "USD",
      "shippingCost": 0,
      "type": "IRL",
      "min_value": 3248,
      "max_value": 3248,
      "category": null,  
      "min_rarity": "legendary",
      "max_rarity": "legendary",
      "released_at": new Date("2021-07-29T03:00:00.000Z"),
      "market": null,
      "category": [
        new mongoose.Types.ObjectId('636c84ece4830d466abadc0d') 
      ]
  },
  {
      "name": "1 Retro High Trophy Room Chicago",
      "icon_url": "https://imgix.ancientgaming.io/images/Jordan%201%20Retro%20High%20Trophy%20Room%20Chicago.png?format=auto",
      "description": "",
      "brand": "Jordan",
      "value": 1898.57,
      "usable": true,
      "obtainable": true,
      "withdrawable": true,
      "rarity": "legendary",
      "currency": "USD",
      "shippingCost": 0,
      "type": "IRL",
      "min_value": 1898.57,
      "max_value": 1898.57,
      "category": null,  
      "min_rarity": "legendary",
      "max_rarity": "legendary",
      "released_at": new Date("2021-02-10T03:00:00.000Z"),
      "market": null,
      "category": [
          new mongoose.Types.ObjectId('636c84ece4830d466abadc21'),
          new mongoose.Types.ObjectId('636c84ece4830d466abadc22')
      ]
  },
  {
      "name": "Painted Camo Crinkle Down Jacket",
      "icon_url": "https://imgix.ancientgaming.io/images/Supreme%20Stone%20Island%20Painted%20Camo%20Crinkle%20Down%20Jacket%20Coral.png?format=auto",
      "description": "",
      "brand": "Supreme x Stone Island",
      "value": 2330,
      "usable": true,
      "obtainable": true,
      "withdrawable": true,
      "rarity": "legendary",
      "currency": "USD",
      "shippingCost": 0,
      "type": "IRL",
      "min_value": 2330,
      "max_value": 2330,
      "category": null,  
      "min_rarity": "legendary",
      "max_rarity": "legendary",
      "released_at": new Date("2020-11-19T03:00:00.000Z"),
      "market": null,
      "category": [
        new mongoose.Types.ObjectId('636c84ece4830d466abadc1f'),
        new mongoose.Types.ObjectId('636c84ece4830d466abadc20'),
        new mongoose.Types.ObjectId('636c84ece4830d466abadc21'),
        new mongoose.Types.ObjectId('636c84ece4830d466abadc22'),
        new mongoose.Types.ObjectId('636c84ece4830d466abadc23')
      ]
  },
  {
      "name": "Jordan 1 Retro High Travis Scott",
      "icon_url": "https://imgix.ancientgaming.io/images/Jordan%201%20Retro%20High%20Travis%20Scott.png?format=auto",
      "description": "",
      "brand": "Nike",
      "value": 1916.43,
      "usable": true,
      "obtainable": true,
      "withdrawable": true,
      "rarity": "legendary",
      "currency": "USD",
      "shippingCost": 0,
      "type": "IRL",
      "min_value": 1916.43,
      "max_value": 1916.43,
      "category": null,  
      "min_rarity": "legendary",
      "max_rarity": "legendary",
      "released_at": new Date("2019-05-11T03:00:00.000Z"),
      "market": null,
      "category": [
        new mongoose.Types.ObjectId('636c84ece4830d466abadc23')
      ]
  },
  {
      "name": "Dionysus Denim Shoulder Bag",
      "icon_url": "https://static.ancientgaming.io/images/Gucci%20Dionysus%20Denim%20Shoulder%20Bag.png",
      "description": "",
      "brand": "Gucci",
      "value": 2980,
      "usable": true,
      "obtainable": true,
      "withdrawable": true,
      "rarity": "legendary",
      "currency": "USD",
      "shippingCost": 0,
      "type": "IRL",
      "min_value": 2980,
      "max_value": 2980,
      "category": null,  
      "min_rarity": "legendary",
      "max_rarity": "legendary",
      "released_at": new Date("2015-06-27T03:00:00.000Z"),
      "market": null,
      "category": [
        new mongoose.Types.ObjectId('636c84ece4830d466abadc1e')
      ]
  },
  {
      "name": "Varsity Leather Jacket",
      "icon_url": "https://static.ancientgaming.io/images/Varsity%20Leather%20Jacket.png",
      "description": "",
      "brand": "Off-White",
      "value": 2655,
      "usable": true,
      "obtainable": true,
      "withdrawable": true,
      "rarity": "legendary",
      "currency": "USD",
      "shippingCost": 0,
      "type": "IRL",
      "min_value": 2655,
      "max_value": 2655,
      "category": null,  
      "min_rarity": "legendary",
      "max_rarity": "legendary",
      "released_at": new Date("2015-06-27T03:00:00.000Z"),
      "market": null,
      "category": [
        new mongoose.Types.ObjectId('636c84ece4830d466abadc19'),
        new mongoose.Types.ObjectId('636c84ece4830d466abadc1a'),
        new mongoose.Types.ObjectId('636c84ece4830d466abadc1b')
      ]
  },
  {
      "name": "1 Retro Shattered Backboard",
      "icon_url": "https://static.ancientgaming.io/images/Jordan%201%20Retro%20Shattered%20Backboard.png",
      "description": "",
      "brand": "Jordan",
      "value": 1663.75,
      "usable": true,
      "obtainable": true,
      "withdrawable": true,
      "rarity": "legendary",
      "currency": "USD",
      "shippingCost": 0,
      "type": "IRL",
      "min_value": 1663.75,
      "max_value": 1663.75,
      "category": null,  
      "min_rarity": "legendary",
      "max_rarity": "legendary",
      "released_at": new Date("2015-06-27T03:00:00.000Z"),
      "market": null,
      "category": [
        new mongoose.Types.ObjectId('636c84ece4830d466abadc18') 
      ]
  },
  {
      "name": "Eyewear CatStyle Frame Sunglasses",
      "icon_url": "https://static.ancientgaming.io/images/Dior%20Eyewear%20CatStyle%20frame%20sunglasses.png",
      "description": "",
      "brand": "Dior",
      "value": 1310,
      "usable": true,
      "obtainable": true,
      "withdrawable": true,
      "rarity": "legendary",
      "currency": "USD",
      "shippingCost": 0,
      "type": "IRL",
      "min_value": 1310,
      "max_value": 1310,
      "category": null,  
      "min_rarity": "legendary",
      "max_rarity": "legendary",
      "released_at": new Date("2018-11-07T02:00:00.000Z"),
      "market": null,
      "category": [
        new mongoose.Types.ObjectId('636c84ece4830d466abadc16') 
      ]
  },
  {
      "name": "1 Retro High \"Not for Resale\" Varsity Red",
      "icon_url": "https://static.ancientgaming.io/images/Jordan%201%20Retro%20High%20Not%20for%20Resale%20Varsity%20Red.png",
      "description": "",
      "brand": "Jordan",
      "value": 1090.71,
      "usable": true,
      "obtainable": true,
      "withdrawable": true,
      "rarity": "legendary",
      "currency": "USD",
      "shippingCost": 0,
      "type": "IRL",
      "min_value": 1090.71,
      "max_value": 1090.71,
      "category": null,  
      "min_rarity": "legendary",
      "max_rarity": "legendary",
      "released_at": new Date("2018-11-07T02:00:00.000Z"),
      "market": null,
      "category": [
        new mongoose.Types.ObjectId('636c84ece4830d466abadc0d')
      ]
  },
  {
      "name": "Lens-decal Square Sunglasses",
      "icon_url": "https://static.ancientgaming.io/images/Bape%20Lens-decal%20Square%20Sunglasses.png",
      "description": "",
      "brand": "Bape",
      "value": 955,
      "usable": true,
      "obtainable": true,
      "withdrawable": true,
      "rarity": "legendary",
      "currency": "USD",
      "shippingCost": 0,
      "type": "IRL",
      "min_value": 955,
      "max_value": 955,
      "category": null,  
      "min_rarity": "legendary",
      "max_rarity": "legendary",
      "released_at": new Date("2018-11-07T02:00:00.000Z"),
      "market": null,
      "category": [
        new mongoose.Types.ObjectId('636c84ece4830d466abadc0c') 
      ]
  },
  {
      "name": "1 Retro High Bred Toe",
      "icon_url": "https://imgix.ancientgaming.io/images/Jordan%201%20Retro%20High%20Bred%20Toe.png?format=auto",
      "description": "",
      "brand": "Jordan",
      "value": 734.38,
      "usable": true,
      "obtainable": true,
      "withdrawable": true,
      "rarity": "epic",
      "currency": "USD",
      "shippingCost": 0,
      "type": "IRL",
      "min_value": 734.38,
      "max_value": 734.38,
      "category": null,  
      "min_rarity": "epic",
      "max_rarity": "rare",
      "released_at": new Date("2018-02-24T03:00:00.000Z"),
      "market": null,
      "category": [
        new mongoose.Types.ObjectId('636c84ece4830d466abadc13'),
        new mongoose.Types.ObjectId('636c84ece4830d466abadc14'),
        new mongoose.Types.ObjectId('636c84ece4830d466abadc15')
      ]
  },
  {
      "name": "Crofton Packable Padded Jacket",
      "icon_url": "https://static.ancientgaming.io/images/Crofton%20Packable%20Padded%20Jacket.png",
      "description": "",
      "brand": "Canada Goose",
      "value": 723.75,
      "usable": true,
      "obtainable": true,
      "withdrawable": true,
      "rarity": "epic",
      "currency": "USD",
      "shippingCost": 0,
      "type": "IRL",
      "min_value": 723.75,
      "max_value": 723.75,
      "category": null,  
      "min_rarity": "epic",
      "max_rarity": "epic",
      "released_at": new Date(),
      "market": null,
      "category": [
        new mongoose.Types.ObjectId('636c84ece4830d466abadc19'),
        new mongoose.Types.ObjectId('636c84ece4830d466abadc1a'),
        new mongoose.Types.ObjectId('636c84ece4830d466abadc1b')
      ]
  },
  {
      "name": "Jordan 4 Retro Bred (2019)",
      "icon_url": "https://imgix.ancientgaming.io/images/Jordan%204%20Retro%20Bred%20(2019).png?format=auto",
      "description": "",
      "brand": "Nike",
      "value": 625,
      "usable": true,
      "obtainable": true,
      "withdrawable": true,
      "rarity": "epic",
      "currency": "USD",
      "shippingCost": 0,
      "type": "IRL",
      "min_value": 625,
      "max_value": 625,
      "category": null,  
      "min_rarity": "epic",
      "max_rarity": "epic",
      "released_at": new Date("2019-05-04T03:00:00.000Z"),
      "market": null,
      "category": [
        new mongoose.Types.ObjectId('636c84ece4830d466abadc1f')
      ]
  },
  {
      "name": "Tie Dye Logo Crewneck Sweatshirt",
      "icon_url": "https://static.ancientgaming.io/images/Saint%20Laurent%20Tie%20Dye%20Logo%20Crewneck%20Sweatshirt.png",
      "description": "",
      "brand": "Saint Laurent",
      "value": 894,
      "usable": true,
      "obtainable": true,
      "withdrawable": true,
      "rarity": "epic",
      "currency": "USD",
      "shippingCost": 0,
      "type": "IRL",
      "min_value": 894,
      "max_value": 894,
      "category": null,  
      "min_rarity": "epic",
      "max_rarity": "epic",
      "released_at": new Date(),
      "market": null,
      "category": [
        new mongoose.Types.ObjectId('636c84ece4830d466abadc21')
      ]
  },
  {
      "name": "Patchwork-detail Denim Jeans",
      "icon_url": "https://static.ancientgaming.io/images/Amiri%20Patchwork-detail%20Denim%20Jeans.png",
      "description": "",
      "brand": "Amiri",
      "value": 1989,
      "usable": true,
      "obtainable": true,
      "withdrawable": true,
      "rarity": "legendary",
      "currency": "USD",
      "shippingCost": 0,
      "type": "IRL",
      "min_value": 1989,
      "max_value": 1989,
      "category": null,  
      "min_rarity": "legendary",
      "max_rarity": "legendary",
      "released_at": new Date(),
      "market": null,
      "category": [
        new mongoose.Types.ObjectId('636c84ece4830d466abadc1b')
      ]
  },
  {
      "name": "Logo Zipped Hooded Jacket",
      "icon_url": "https://static.ancientgaming.io/images/A-Cold-Wall%20Logo%20Zipped%20Hooded%20Jacket.png",
      "description": "",
      "brand": "A-Cold-Wall",
      "value": 1278,
      "usable": true,
      "obtainable": true,
      "withdrawable": true,
      "rarity": "legendary",
      "currency": "USD",
      "shippingCost": 0,
      "type": "IRL",
      "min_value": 1278,
      "max_value": 1278,
      "category": null,  
      "min_rarity": "legendary",
      "max_rarity": "legendary",
      "released_at": new Date(),
      "market": null,
      "category": [
        new mongoose.Types.ObjectId('636c84ece4830d466abadc12')
      ]
    },
  {
        "name": "Oversized Oblique T-shirt",
        "icon_url": "https://static.ancientgaming.io/images/Dior%20Oversized%20Oblique%20T-shirt%20White.png",
        "description": "",
        "brand": "Dior",
        "value": 833.33,
        "usable": true,
        "obtainable": true,
        "withdrawable": true,
        "currency": "USD",
        "min_value": 800,
        "max_value": 850,
        "shipping_cost": 0,
        "type": "IRL",
        "rarity": "legendary",
        "min_rarity": "epic",
        "max_rarity": "legendary",
        "released_at": new Date(),
        "market": null,
        "category": [
            new mongoose.Types.ObjectId('636c84ece4830d466abadc0e')
        ]
    },
    {
        "name": "1 Retro High Bred Toe",
        "icon_url": "https://imgix.ancientgaming.io/images/Jordan%201%20Retro%20High%20Bred%20Toe.png?format=auto",
        "description": "",
        "brand": "Jordan",
        "value": 734.38,
        "usable": true,
        "obtainable": true,
        "withdrawable": true,
        "min_value": 670,
        "max_value": 920,
        "currency": "USD",
        "shipping_cost": 0,
        "type": "IRL",
        "rarity": "rare",
        "min_rarity": "epic",
        "max_rarity": "rare",
        "released_at": new Date("2018-02-24T03:00:00.000Z"),
        "market": null,
        "category": [
            new mongoose.Types.ObjectId('636c84ece4830d466abadc0d') 
        ]
    },
    {
        "name": "Crofton Packable Padded Jacket",
        "icon_url": "https://static.ancientgaming.io/images/Crofton%20Packable%20Padded%20Jacket.png",
        "description": "",
        "brand": "Canada Goose",
        "value": 723.75,
        "usable": true,
        "obtainable": true,
        "withdrawable": true,
        "currency": "USD",
        "min_value": 715,
        "max_value": 750,
        "shipping_cost": 0,
        "type": "IRL",
        "rarity": "epic",
        "min_rarity": "epic",
        "max_rarity": "epic",
        "released_at": new Date(),
        "market": null,
        "category": [
            new mongoose.Types.ObjectId('636c84ece4830d466abadc0c')
        ]
    },
    {
        "name": "Jordan 4 Retro Bred (2019)",
        "icon_url": "https://imgix.ancientgaming.io/images/Jordan%204%20Retro%20Bred%20(2019).png?format=auto",
        "description": "",
        "brand": "Nike",
        "value": 625,
        "usable": true,
        "obtainable": true,
        "withdrawable": true,
        "min_value": 600,
        "max_value": 665,
        "currency": "USD",
        "shipping_cost": 0,
        "type": "IRL",
        "rarity": "epic",
        "min_rarity": "epic",
        "max_rarity": "epic",
        "released_at": new Date("2019-05-04T03:00:00.000Z"),
        "market": null,
        "category": [
            new mongoose.Types.ObjectId('636c84ece4830d466abadc19')
        ]
    },
    {
        "name": "Tie Dye Logo Crewneck Sweatshirt",
        "icon_url": "https://static.ancientgaming.io/images/Saint%20Laurent%20Tie%20Dye%20Logo%20Crewneck%20Sweatshirt.png",
        "description": "",
        "brand": "Saint Laurent",
        "value": 894,
        "usable": true,
        "obtainable": true,
        "withdrawable": true,
        "currency": "USD",
        "min_value": 790,
        "max_value": 998,
        "shipping_cost": 0,
        "type": "IRL",
        "rarity": "epic",
        "min_rarity": "epic",
        "max_rarity": "epic",
        "released_at": new Date(),
        "market": null,
        "category": [
            new mongoose.Types.ObjectId('636c84ece4830d466abadc1e')
        ]
    },
    {
        "name": "Patchwork-detail Denim Jeans",
        "icon_url": "https://static.ancientgaming.io/images/Amiri%20Patchwork-detail%20Denim%20Jeans.png",
        "description": "",
        "brand": "Amiri",
        "value": 1989,
        "usable": true,
        "obtainable": true,
        "withdrawable": true,
        "currency": "USD",
        "min_value": 1920,
        "max_value": 2035,
        "shipping_cost": 0,
        "type": "IRL",
        "rarity": "legendary",
        "min_rarity": "legendary",
        "max_rarity": "legendary",
        "released_at": new Date(),
        "market": null,
        "category": [
            new mongoose.Types.ObjectId('636c84ece4830d466abadc22'),
            new mongoose.Types.ObjectId('636c84ece4830d466abadc23')
        ]
    },
    {
        "name": "Logo Zipped Hooded Jacket",
        "icon_url": "https://static.ancientgaming.io/images/A-Cold-Wall%20Logo%20Zipped%20Hooded%20Jacket.png",
        "description": "",
        "brand": "A-Cold-Wall",
        "value": 1278,
        "usable": true,
        "obtainable": true,
        "withdrawable": true,
        "currency": "USD",
        "min_value": 1278,
        "max_value": 1278,
        "shipping_cost": 0,
        "type": "IRL",
        "rarity": "legendary",
        "min_rarity": "legendary",
        "max_rarity": "legendary",
        "released_at": new Date(),
        "market": null,
        "category": [
            new mongoose.Types.ObjectId('636c84ece4830d466abadc11')
        ]
    },
    {
        "name": "Distressed Slim-fit Jeans",
        "icon_url": "https://static.ancientgaming.io/images/Dsquared2%20Distressed%20Slim-fit%20Jeans.png",
        "description": "",
        "brand": "Dsquared2",
        "value": 650,
        "usable": true,
        "obtainable": true,
        "withdrawable": true,
        "currency": "USD",
        "min_value": 615,
        "max_value": 720,
        "shipping_cost": 0,
        "type": "IRL",
        "rarity": "epic",
        "min_rarity": "epic",
        "max_rarity": "epic",
        "released_at": new Date(),
        "market": null,
        "category": [
            new mongoose.Types.ObjectId('636c84ece4830d466abadc0f')
        ]
    },
    {
        "name": "3 Retro Cardinal Red",
        "icon_url": "https://static.ancientgaming.io/images/Jordan%203%20Retro%20cardinal%20red.png",
        "description": "",
        "brand": "Jordan",
        "value": 256.25,
        "usable": true,
        "obtainable": true,
        "withdrawable": true,
        "min_value": 245,
        "max_value": 270,
        "currency": "USD",
        "shipping_cost": 0,
        "type": "IRL",
        "rarity": "rare",
        "min_rarity": "rare",
        "max_rarity": "rare",
        "released_at": new Date("2022-02-18T03:00:00.000Z"),
        "market": null,
        "category": [
            new mongoose.Types.ObjectId('636c84ece4830d466abadc18')
        ]
    },
    {
        "name": "1 Retro High Spider-Man Origin Story",
        "icon_url": "https://static.ancientgaming.io/images/Jordan%201%20Retro%20High%20Spider-Man%20Origin%20Story.png",
        "description": "",
        "brand": "Jordan",
        "value": 952.5,
        "usable": true,
        "obtainable": true,
        "withdrawable": true,
        "min_value": 775,
        "max_value": 1200,
        "currency": "USD",
        "shipping_cost": 0,
        "type": "IRL",
        "rarity": "legendary",
        "min_rarity": "epic",
        "max_rarity": "legendary",
        "released_at": new Date("2018-12-14T02:00:00.000Z"),
        "market": null,
        "category": [
            new mongoose.Types.ObjectId('636c84ece4830d466abadc15')
        ]
    },
    {
        "name": "Cross Box Logo Hooded Sweatshirt Heather",
        "icon_url": "https://imgix.ancientgaming.io/images/Supreme%20Cross%20Box%20Logo%20Hooded%20Sweatshirt%20Heather%20Grey.png?format=auto",
        "description": "",
        "brand": "Supreme",
        "value": 395,
        "usable": true,
        "obtainable": true,
        "withdrawable": true,
        "min_value": 385,
        "max_value": 405,
        "currency": "USD",
        "shipping_cost": 0,
        "type": "IRL",
        "rarity": "rare",
        "min_rarity": "rare",
        "max_rarity": "rare",
        "released_at": new Date("2020-12-03T03:00:00.000Z"),
        "market": null,
        "category": [
            new mongoose.Types.ObjectId('636c84ece4830d466abadc11')
        ]
    },
    {
        "name": "Logo-print Cotton T-shirt",
        "icon_url": "https://static.ancientgaming.io/images/Dolce%20%26%20Gabbana%20logo-print%20cotton%20T-shirt.png",
        "description": "",
        "brand": "Dolce & Gabbana",
        "value": 595,
        "usable": true,
        "obtainable": true,
        "withdrawable": true,
        "currency": "USD",
        "min_value": 595,
        "max_value": 595,
        "shipping_cost": 0,
        "type": "IRL",    
        "rarity": "epic",
        "min_rarity": "epic",
        "max_rarity": "epic",
        "released_at": new Date(),
        "market": null,
        "category": [
            new mongoose.Types.ObjectId('636c84ece4830d466abadc0c')
        ]
    },
    {
        "name": "Half Zip Hooded Sweatshirt",
        "icon_url": "https://static.ancientgaming.io/images/Supreme%20Nike%20Half%20Zip%20Hooded%20Sweatshirt%20Black.png",
        "description": "",
        "brand": "Supreme x Nike",
        "value": 203.33,
        "usable": true,
        "obtainable": true,
        "withdrawable": true,
        "min_value": 190,
        "max_value": 210,
        "currency": "USD",
        "shipping_cost": 0,
        "type": "IRL",
        "rarity": "rare",
        "min_rarity": "rare",
        "max_rarity": "rare",
        "released_at": new Date("2021-03-11T03:00:00.000Z"),
        "market": null,
        "category": [
            new mongoose.Types.ObjectId('636c84ece4830d466abadc1c')
        ]
    },
    {
        "name": "Logo-print Crew Neck Sweatshirt",
        "icon_url": "https://static.ancientgaming.io/images/Alexander%20McQueen%20Logo-print%20Crew%20Neck%20Sweatshirt.png",
        "description": "",
        "brand": "Alexander McQueen",
        "value": 680,
        "usable": true,
        "obtainable": true,
        "withdrawable": true,
        "currency": "USD",
        "min_value": 680,
        "max_value": 680,
        "shipping_cost": 0,
        "type": "IRL",      
        "rarity": "epic",
        "min_rarity": "epic",
        "max_rarity": "epic",
        "released_at": new Date(),
        "market": null,
        "category": [
            new mongoose.Types.ObjectId('636c84ece4830d466abadc1e')
        ]
    },
    {
        "name": "Box Logo Hooded Sweatshirt (FW21) Black",
        "icon_url": "https://static.ancientgaming.io/images/Supreme%20Box%20Logo%20Hooded%20Sweatshirt%20(FW21)%20Black.png",
        "description": "",
        "brand": "Supreme",
        "value": 380,
        "usable": true,
        "obtainable": true,
        "withdrawable": true,
        "min_value": 320,
        "max_value": 410,
        "currency": "USD",
        "shipping_cost": 0,
        "type": "IRL",
        "rarity": "rare",
        "min_rarity": "rare",
        "max_rarity": "rare",
        "released_at": new Date("2021-12-08T16:00:00.000Z"),
        "market": null,
        "category": [
            new mongoose.Types.ObjectId('636c84ece4830d466abadc16'),
            new mongoose.Types.ObjectId('636c84ece4830d466abadc17'),
            new mongoose.Types.ObjectId('636c84ece4830d466abadc18'),
            new mongoose.Types.ObjectId('636c84ece4830d466abadc19') 
        ]
    },
    {
        "name": "1 Mid Chicago Toe",
        "icon_url": "https://imgix.ancientgaming.io/images/Jordan%201%20Mid%20Chicago%20Toe.png?format=auto",
        "description": "",
        "brand": "Jordan",
        "value": 322.86,
        "usable": true,
        "obtainable": true,
        "withdrawable": true,
        "min_value": 235,
        "max_value": 395,
        "currency": "USD",
        "shipping_cost": 0,
        "type": "IRL",
        "rarity": "rare",
        "min_rarity": "rare",
        "max_rarity": "rare",
        "released_at": new Date("2020-04-01T03:00:00.000Z"),
        "market": null,
        "category": [
            new mongoose.Types.ObjectId('636c84ece4830d466abadc13')
        ]
    },
    {
        "name": "1 Retro High Royal Toe",
        "icon_url": "https://imgix.ancientgaming.io/images/Jordan%201%20Retro%20High%20Royal%20Toe.png?format=auto",
        "description": "",
        "brand": "Jordan",
        "value": 319.38,
        "usable": true,
        "obtainable": true,
        "withdrawable": true,
        "min_value": 285,
        "max_value": 395,
        "currency": "USD",
        "shipping_cost": 0,
        "type": "IRL",
        "rarity": "rare",
        "min_rarity": "rare",
        "max_rarity": "rare",
        "released_at": new Date("2020-05-09T03:00:00.000Z"),
        "market": null,
        "category": [
            new mongoose.Types.ObjectId('636c84ece4830d466abadc23')
        ]
    },
    {
        "name": "1 Zoom Air CMFT PSG Paris Saint-Germain",
        "icon_url": "https://imgix.ancientgaming.io/images/Jordan%201%20Zoom%20Air%20CMFT%20PSG%20Paris%20Saint-Germain.png?format=auto",
        "description": "",
        "brand": "Jordan",
        "value": 314.44,
        "usable": true,
        "obtainable": true,
        "withdrawable": true,
        "min_value": 260,
        "max_value": 510,
        "currency": "USD",
        "shipping_cost": 0,
        "type": "IRL",
        "rarity": "rare",
        "min_rarity": "rare",
        "max_rarity": "rare",
        "released_at": new Date("2021-02-17T03:00:00.000Z"),
        "market": null,
        "category": [
            new mongoose.Types.ObjectId('636c84ece4830d466abadc15')
        ]
    },
    {
        "name": "1 Retro High Light Smoke Grey",
        "icon_url": "https://imgix.ancientgaming.io/images/Jordan%201%20Retro%20High%20Light%20Smoke%20Grey.png?format=auto",
        "description": "",
        "brand": "Jordan",
        "value": 276.67,
        "usable": true,
        "obtainable": true,
        "withdrawable": true,
        "min_value": 255,
        "max_value": 300,
        "currency": "USD",
        "shipping_cost": 0,
        "type": "IRL",
        "rarity": "rare",
        "min_rarity": "rare",
        "max_rarity": "rare",
        "released_at": new Date("2020-07-11T03:00:00.000Z"),
        "market": null,
        "category": [
            new mongoose.Types.ObjectId('636c84ece4830d466abadc12') 
        ]
    },
    {
        "name": "Logo-print Track Pants",
        "icon_url": "https://static.ancientgaming.io/images/Palm%20Angels%20Logo-print%20Track%20Pants.png",
        "description": "",
        "brand": "Palm Angels",
        "value": 470,
        "usable": true,
        "obtainable": true,
        "withdrawable": true,
        "currency": "USD",
        "min_value": 470,
        "max_value": 470,
        "shipping_cost": 0,
        "type": "IRL",   
        "rarity": "rare",
        "min_rarity": "rare",
        "max_rarity": "rare",
        "released_at": new Date(),
        "market": null,
        "category": [
            new mongoose.Types.ObjectId('636c84ece4830d466abadc10')
        ]
    },
    {
        "name": "NRG AG Utility Sweatpants",
        "icon_url": "https://imgix.ancientgaming.io/images/Travis%20Scott%20x%20Nike%20NRG%20AG%20Utility%20Sweatpants%20Black.png?format=auto",
        "description": "",
        "brand": "Travis Scott x Nike",
        "value": 326.67,
        "usable": true,
        "obtainable": true,
        "withdrawable": true,
        "min_value": 255,
        "max_value": 435,
        "currency": "USD",
        "shipping_cost": 0,
        "type": "IRL",
        "rarity": "rare",
        "min_rarity": "rare",
        "max_rarity": "rare",
        "released_at": new Date("2020-05-29T03:00:00.000Z"),
        "market": null,
        "category": [
            new mongoose.Types.ObjectId('636c84ece4830d466abadc0e')
        ]
    },
    {
        "name": "Patched Ribbed Beanie",
        "icon_url": "https://static.ancientgaming.io/images/Moncler%20x%20Palm%20Angels%20Patched%20Ribbed%20Beanie.png",
        "description": "",
        "brand": "Moncler x Palm Angels",
        "value": 305,
        "usable": true,
        "obtainable": true,
        "withdrawable": true,
        "min_value": 305,
        "max_value": 305,
        "currency": "USD",
        "shipping_cost": 0,
        "type": "IRL",
        "rarity": "rare",
        "min_rarity": "rare",
        "max_rarity": "rare",
        "released_at": new Date("2021-12-01T16:00:00.000Z"),
        "market": null,
        "category": [
            new mongoose.Types.ObjectId('636c84ece4830d466abadc1b')
        ]
    },
    {
        "name": "1 Mid Shattered Backboard",
        "icon_url": "https://static.ancientgaming.io/images/Jordan%201%20Mid%20Shattered%20Backboard.png",
        "description": "",
        "brand": "Jordan",
        "value": 280.83,
        "usable": true,
        "obtainable": true,
        "withdrawable": true,
        "min_value": 240,
        "max_value": 350,
        "currency": "USD",
        "shipping_cost": 0,
        "type": "IRL",
        "rarity": "rare",
        "min_rarity": "rare",
        "max_rarity": "rare",
        "released_at": new Date("2019-09-07T03:00:00.000Z"),
        "market": null,
        "category": [
            new mongoose.Types.ObjectId('636c84ece4830d466abadc21')
        ]
    },
    {
        "name": "1 Low Game Royal",
        "icon_url": "https://imgix.ancientgaming.io/images/Jordan%201%20Low%20Game%20Royal.png?format=auto",
        "description": "",
        "brand": "Jordan",
        "value": 257,
        "usable": true,
        "obtainable": true,
        "withdrawable": true,
        "min_value": 230,
        "max_value": 300,
        "currency": "USD",
        "shipping_cost": 0,
        "type": "IRL",
        "rarity": "rare",
        "min_rarity": "rare",
        "max_rarity": "rare",
        "released_at": new Date("2020-07-24T03:00:00.000Z"),
        "market": null,
        "category": [
            new mongoose.Types.ObjectId('636c84ece4830d466abadc0d')
        ]
    },
    {
        "name": "1 Retro High Satin Snake Chicago (W)",
        "icon_url": "https://static.ancientgaming.io/images/Jordan%201%20Retro%20High%20Satin%20Snake%20Chicago%20(W).png",
        "description": "",
        "brand": "Jordan",
        "value": 249.38,
        "usable": true,
        "obtainable": true,
        "withdrawable": true,
        "min_value": 220,
        "max_value": 295,
        "currency": "USD",
        "shipping_cost": 0,
        "type": "IRL",
        "rarity": "rare",
        "min_rarity": "rare",
        "max_rarity": "rare",
        "released_at": new Date("2020-08-06T03:00:00.000Z"),
        "market": null,
        "category": [
            new mongoose.Types.ObjectId('636c84ece4830d466abadc16'),
            new mongoose.Types.ObjectId('636c84ece4830d466abadc17'),
            new mongoose.Types.ObjectId('636c84ece4830d466abadc18'),
            new mongoose.Types.ObjectId('636c84ece4830d466abadc19'),
            new mongoose.Types.ObjectId('636c84ece4830d466abadc1a'),
            new mongoose.Types.ObjectId('636c84ece4830d466abadc1b')
        ]
    }
]